# https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
version: '3.5'
# name: 'myproject'

services:
  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-nginx
    ports:
      - '80:80'
    volumes:
      - ./code:/code # example html page
      - ./docker/nginx/vhost:/etc/nginx/conf.d/default.conf #configuration of vhost for nginx
    links:
      - php
      - mysql

  # setup php
  php:
    container_name: ${PROJECT_NAME}-php
    image: 'php:alpine'
    build:
      context: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./code:/code

  # mysql
  mysql:
    container_name: ${PROJECT_NAME}-mysql
    build:
      context: ./docker/mysql
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
